/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LeaveRequestsRouteImport } from './routes/leave-requests'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationsIdRouteImport } from './routes/stations.$id'
import { Route as LeaveRequestsIdRouteImport } from './routes/leave-requests.$id'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'

const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRequestsRoute = LeaveRequestsRouteImport.update({
  id: '/leave-requests',
  path: '/leave-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsIdRoute = StationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StationsRoute,
} as any)
const LeaveRequestsIdRoute = LeaveRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LeaveRequestsRoute,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/leave-requests': typeof LeaveRequestsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/stations': typeof StationsRouteWithChildren
  '/employees/$id': typeof EmployeesIdRoute
  '/leave-requests/$id': typeof LeaveRequestsIdRoute
  '/stations/$id': typeof StationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/leave-requests': typeof LeaveRequestsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/stations': typeof StationsRouteWithChildren
  '/employees/$id': typeof EmployeesIdRoute
  '/leave-requests/$id': typeof LeaveRequestsIdRoute
  '/stations/$id': typeof StationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/leave-requests': typeof LeaveRequestsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/stations': typeof StationsRouteWithChildren
  '/employees/$id': typeof EmployeesIdRoute
  '/leave-requests/$id': typeof LeaveRequestsIdRoute
  '/stations/$id': typeof StationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employees'
    | '/leave-requests'
    | '/reports'
    | '/stations'
    | '/employees/$id'
    | '/leave-requests/$id'
    | '/stations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employees'
    | '/leave-requests'
    | '/reports'
    | '/stations'
    | '/employees/$id'
    | '/leave-requests/$id'
    | '/stations/$id'
  id:
    | '__root__'
    | '/'
    | '/employees'
    | '/leave-requests'
    | '/reports'
    | '/stations'
    | '/employees/$id'
    | '/leave-requests/$id'
    | '/stations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeesRoute: typeof EmployeesRouteWithChildren
  LeaveRequestsRoute: typeof LeaveRequestsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  StationsRoute: typeof StationsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave-requests': {
      id: '/leave-requests'
      path: '/leave-requests'
      fullPath: '/leave-requests'
      preLoaderRoute: typeof LeaveRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$id': {
      id: '/stations/$id'
      path: '/$id'
      fullPath: '/stations/$id'
      preLoaderRoute: typeof StationsIdRouteImport
      parentRoute: typeof StationsRoute
    }
    '/leave-requests/$id': {
      id: '/leave-requests/$id'
      path: '/$id'
      fullPath: '/leave-requests/$id'
      preLoaderRoute: typeof LeaveRequestsIdRouteImport
      parentRoute: typeof LeaveRequestsRoute
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
  }
}

interface EmployeesRouteChildren {
  EmployeesIdRoute: typeof EmployeesIdRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesIdRoute: EmployeesIdRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

interface LeaveRequestsRouteChildren {
  LeaveRequestsIdRoute: typeof LeaveRequestsIdRoute
}

const LeaveRequestsRouteChildren: LeaveRequestsRouteChildren = {
  LeaveRequestsIdRoute: LeaveRequestsIdRoute,
}

const LeaveRequestsRouteWithChildren = LeaveRequestsRoute._addFileChildren(
  LeaveRequestsRouteChildren,
)

interface StationsRouteChildren {
  StationsIdRoute: typeof StationsIdRoute
}

const StationsRouteChildren: StationsRouteChildren = {
  StationsIdRoute: StationsIdRoute,
}

const StationsRouteWithChildren = StationsRoute._addFileChildren(
  StationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeesRoute: EmployeesRouteWithChildren,
  LeaveRequestsRoute: LeaveRequestsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  StationsRoute: StationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
