/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/employees/$id': typeof EmployeesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/employees/$id': typeof EmployeesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/employees/$id': typeof EmployeesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attendance' | '/employees' | '/settings' | '/employees/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attendance' | '/employees' | '/settings' | '/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/employees'
    | '/settings'
    | '/employees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  EmployeesRoute: typeof EmployeesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
  }
}

interface EmployeesRouteChildren {
  EmployeesIdRoute: typeof EmployeesIdRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesIdRoute: EmployeesIdRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  EmployeesRoute: EmployeesRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
